# Generated by Django 3.2.5 on 2022-06-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_name', models.TextField()),
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play_List',
            fields=[
                ('play_list_name', models.TextField()),
                ('is_public', models.BooleanField()),
                ('play_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.logging_user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.movies')),
                ('playList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.play_list')),
            ],
        ),
    ]
