# Generated by Django 3.2.5 on 2022-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_movies_play_list_playlist_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_omdbId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
